### ISSUE TITLE
Uploading a new movie

### ISSUE THREAD

**Issue by badjem79** [NicholasLiem/IF3110_M1_BondFlix#1]
When i try to upload a new movie i get this error:
![image](https://github.com/NicholasLiem/IF3110_M1_BondFlix/assets/5801803/882ed1b8-1503-4bf5-ad60-62706406f46c)
and no movie is uploaded
how do i upload movies in a different way, like manually?

**Comment by NicholasLiem** [comment]
Hey Fabio,
Thanks for looking out on my repository. I think there is an error with either the title and description that causes the Unexpected token '<', "br/>" stuff. Try to make a new content and put in just enough title and description without newlines or anything it should fix that error. Apparently this repository does not support uploading movies in a different way like manually.

Maybe if you could provide me with the JSON request payload via the Network Developer Tools that would be great!

**Comment by badjem79** [comment]
ok, I understood the problem
this is the (not) json response
`
Warning: POST Content-Length of 909955115 bytes exceeds the limit of 104857600 bytes in Unknown on line 0

Warning: session_start(): Session cannot be started after headers have already been sent in /var/www/html/index.php on line 3

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 100212768 bytes) in /var/www/html/Router/Router.php on line 54
`

Indeed a small video works fine...

How do I change the file size limit?

**Comment by badjem79** [comment]
Ok, I changed php.ini upload_max_filesize  and post_max_size  to 2GB, anyway the error should be catched in the php to return a valid json

and also in Utils/Uploader/VideoUploader.php there is the same constant on 100M that has to be updated in order to upload bigger files...

**Comment by NicholasLiem** [comment]
Ah yes, missed about the limit size. Thanks for pointing it out.
